partitionNum=50;
totalLength=2;
partitionLength=totalLength/partitionNum;
nLattice=[1:partitionNum];
[m,n]=meshgrid(nLattice);
x=m*partitionLength-totalLength/2-0.5;
y=n*partitionLength-totalLength/2-0.5;
datasquare=fluxdensitySquare(1,1,1,x,y);
save('datasquare2.mat','datasquare');